Fix small issues (#727)
* Fix pytest dependency conflict

* Mark test as failing

* Fix crash

TypeError: 'set' object is not subscriptable

* Fix force flag not being passed

* Revert xfail